//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreenNumericObserver.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScreenNumericObserver.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Area is on screen out of range.   に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AreaOutOfRange {
            get {
                return ResourceManager.GetString("AreaOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Captured Area に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Captured {
            get {
                return ResourceManager.GetString("Captured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to open file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailedOpenFile {
            get {
                return ResourceManager.GetString("FailedOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to save file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailedSaveFile {
            get {
                return ResourceManager.GetString("FailedSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Log Files(*.log)|*.log|All Files(*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogFileFilter {
            get {
                return ResourceManager.GetString("LogFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set the captured area. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoCapture {
            get {
                return ResourceManager.GetString("NoCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   None に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Observers Files(*.sno)|*.sno に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ObserversFileFilter {
            get {
                return ResourceManager.GetString("ObserversFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Run に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Observing {
            get {
                return ResourceManager.GetString("Observing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rate Changed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RateChanged {
            get {
                return ResourceManager.GetString("RateChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rate Changed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RateChangedDefault {
            get {
                return ResourceManager.GetString("RateChangedDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartObserve {
            get {
                return ResourceManager.GetString("StartObserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StopObserve {
            get {
                return ResourceManager.GetString("StopObserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unrecognized に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Unrecognized {
            get {
                return ResourceManager.GetString("Unrecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Voice Changed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VoiceChanged {
            get {
                return ResourceManager.GetString("VoiceChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Voice Changed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VoiceChangedDefault {
            get {
                return ResourceManager.GetString("VoiceChangedDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Volume Changed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VolumeChanged {
            get {
                return ResourceManager.GetString("VolumeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Volume Changed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VolumeChangedDefault {
            get {
                return ResourceManager.GetString("VolumeChangedDefault", resourceCulture);
            }
        }
    }
}
